### ISSUE TITLE
pre 2016 task list

### ISSUE THREAD

**Issue by nwh** [CME211/notes#7]
- [x] update schedule for first 7 sessions
- [x] add TA office hours somewhere 
- [x] add syllabus to notes repo
- [x] add schedule to notes repo
- [x] update `hw1`
- [x] update `hw2`
- [ ] udpate `hw3`

other questions:
- [ ] sanity check?

Homework repo: https://github.com/CME211/homework
